// Maps our channel id -> Digea EPG channel id.
//
// Generated by scripts/refresh-epg-map.mjs on 2026-09-17.
// Digea (https://www.digea.gr) is the Greek DTT network operator and publishes a
// public schedule API. Covers 56 channels.
//
// ERT channels are absent on purpose: ERT broadcasts on its own multiplex and is
// not carried in Digea's guide, so those cards show "no guide" instead.

export const DIGEA_BY_CHANNEL = {
  4   : 3100 , // Alpha
  5   : 3300 , // Ant1
  6   : 3600 , // Mega
  7   : 3400 , // Open Beyond
  8   : 3200 , // Skai
  9   : 3500 , // Star
  11  : 3700 , // Makedonia TV
  101 : 4380 , // 4E
  102 : 5420 , // Acheloos TV
  103 : 4910 , // Alert
  104 : 4080 , // Alfa
  105 : 4490 , // Art
  106 : 5450 , // Art TV
  108 : 4510 , // Best TV
  110 : 4940 , // One Channel
  111 : 5460 , // Corfu Channel
  112 : 5580 , // Kriti TV
  113 : 4020 , // Delta
  115 : 5720 , // Aigaio TV
  117 : 4040 , // Ena Channel
  118 : 4050 , // Epiloges
  119 : 5440 , // Epirus TV1
  120 : 4950 , // Extra Channel
  121 : 5010 , // High TV
  123 : 4520 , // Ionian Channel
  125 : 5020 , // Kontra
  126 : 4530 , // Lepanto
  127 : 4450 , // Lychnos
  128 : 4460 , // Mesogeios TV
  135 : 5850 , // Syros TV1
  136 : 4060 , // Thrakinet
  137 : 4700 , // TRT TV
  138 : 4300 , // TV 100
  139 : 5610 , // Creta TV
  140 : 5760 , // TV Kosmos
  143 : 4120 , // Star B. Ellados
  144 : 4240 , // Vergina
  147 : 5480 , // Start TV
  148 : 4680 , // Astra TV
  152 : 5150 , // Aeolos TV
  153 : 5350 , // Top Channel
  155 : 4930 , // Blue Sky
  156 : 5000 , // Action 24
  157 : 4810 , // Star K. Ellados
  158 : 4670 , // Thessalia TV
  160 : 4290 , // Gnomi TV
  161 : 5430 , // Vima TV
  539 : 4710 , // FORMedia TV
  541 : 4990 , // Naftemporiki
  622 : 5030 , // Mad TV
  641 : 4090 , // Center TV
  642 : 4270 , // Euro TV
  650 : 4440 , // Ilektra
  657 : 5130 , // Alitheia Tv
  677 : 5750 , // KOS TV
  799 : 4280 , // Pontos TV
};

export const CHANNEL_BY_DIGEA = Object.fromEntries(
  Object.entries(DIGEA_BY_CHANNEL).map(([channelId, digeaId]) => [digeaId, Number(channelId)])
);
