// Regenerates lib/epg-map.js from Digea's live channel list.
//
//   npm run refresh:epg-map
//
// Run this when channels appear or disappear from the guide. It transliterates
// Digea's Greek channel names to Latin and matches them against our catalogue,
// then prints whatever it could not place so you can extend MANUAL below.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { CHANNELS } from "../public/channels.js";
import { fetchDigeaChannels } from "../lib/digea.js";

const OUT = fileURLToPath(new URL("../lib/epg-map.js", import.meta.url));

// Digea channel id -> our channel name, for pairs no rule will ever catch.
const MANUAL = {
  4810: "Star K. Ellados",
  4120: "Star B. Ellados",
  4300: "TV 100",
  5440: "Epirus TV1",
};

const GREEK_LATIN = {
  Α: "A", Β: "V", Γ: "G", Δ: "D", Ε: "E", Ζ: "Z", Η: "I", Θ: "TH", Ι: "I",
  Κ: "K", Λ: "L", Μ: "M", Ν: "N", Ξ: "X", Ο: "O", Π: "P", Ρ: "R", Σ: "S",
  Τ: "T", Υ: "Y", Φ: "F", Χ: "CH", Ψ: "PS", Ω: "O",
};

const translit = (s) =>
  [...s.toUpperCase()].map((c) => (GREEK_LATIN[c] ?? c)).join("");

const norm = (s) => translit(s).toLowerCase().replace(/[^a-z0-9]/g, "");
const base = (s) => norm(s).replace(/^(tileorasi|tv)/, "").replace(/(tileorasi|tv|channel)$/, "");

const byNorm = new Map();
const byBase = new Map();
for (const ch of CHANNELS) {
  if (!byNorm.has(norm(ch.name))) byNorm.set(norm(ch.name), ch);
  const b = base(ch.name);
  if (b && !byBase.has(b)) byBase.set(b, ch);
}
const byName = new Map(CHANNELS.map((c) => [c.name, c]));

const digea = await fetchDigeaChannels();
console.log(`Digea lists ${digea.length} channels.`);

const pairs = new Map(); // our id -> digea id
const unmatched = [];

for (const d of digea) {
  let ch = MANUAL[d.id] ? byName.get(MANUAL[d.id]) : null;
  if (!ch) ch = byNorm.get(norm(d.name)) || byBase.get(base(d.name)) || null;
  if (ch && !pairs.has(ch.id)) pairs.set(ch.id, d.id);
  else if (!ch) unmatched.push(d);
}

const ordered = [...pairs.entries()].sort((a, b) => a[0] - b[0]);
const rows = ordered
  .map(([ours, theirs]) => {
    const name = CHANNELS.find((c) => c.id === ours).name;
    return `  ${String(ours).padEnd(4)}: ${String(theirs).padEnd(5)}, // ${name}`;
  })
  .join("\n");

const file = `// Maps our channel id -> Digea EPG channel id.
//
// Generated by scripts/refresh-epg-map.mjs on ${new Date().toISOString().slice(0, 10)}.
// Digea (https://www.digea.gr) is the Greek DTT network operator and publishes a
// public schedule API. Covers ${ordered.length} channels.
//
// ERT channels are absent on purpose: ERT broadcasts on its own multiplex and is
// not carried in Digea's guide, so those cards show "no guide" instead.

export const DIGEA_BY_CHANNEL = {
${rows}
};

export const CHANNEL_BY_DIGEA = Object.fromEntries(
  Object.entries(DIGEA_BY_CHANNEL).map(([channelId, digeaId]) => [digeaId, Number(channelId)])
);
`;

await writeFile(OUT, file, "utf8");
console.log(`Wrote ${ordered.length} mappings to lib/epg-map.js`);

if (unmatched.length) {
  console.log(`\n${unmatched.length} Digea channels had no match here:`);
  for (const d of unmatched) console.log(`  ${d.id}  ${d.name}`);
  console.log("\nAdd any that belong to a channel in public/channels.js to MANUAL above.");
}
